/**
 * Business-logic wrappers that start OAuth flows for each calendar provider.
 *
 * Keeps the UI layer free of direct data-provider imports per the architecture
 * rule that UI never touches calendar APIs directly. The `sign-in` and
 * `settings` routes call these instead of importing from `app/data/providers/`.
 */

import { startGoogleAuth } from "../data/providers/google";
import {
  CALENDAR_CONNECTION_SCOPE as GOOGLE_CALENDAR_CONNECTION_SCOPE,
  IDENTITY_SCOPE as GOOGLE_IDENTITY_SCOPE,
} from "../data/providers/google/auth";
import {
  GOOGLE_CLIENT_ID,
  googleRedirectUri,
  isGoogleConfigured,
} from "../data/providers/google/config";
import { startOutlookAuth } from "../data/providers/outlook";
import {
  CALENDAR_CONNECTION_SCOPE as OUTLOOK_CALENDAR_CONNECTION_SCOPE,
  IDENTITY_SCOPE as OUTLOOK_IDENTITY_SCOPE,
} from "../data/providers/outlook/auth";
import {
  OUTLOOK_CLIENT_ID,
  isOutlookConfigured,
  outlookRedirectUri,
} from "../data/providers/outlook/config";
import { setPostAuthRedirect, type OAuthIntent, type PendingOAuthFlow } from "./authState";

/** Options for the OAuth sign-in initiators. */
export interface StartSignInOptions {
  /** Where to redirect after OAuth completes; defaults to the timeline root. */
  returnTo?: string;
}

type OAuthFlowInput = Pick<PendingOAuthFlow, "provider" | "returnTo"> & {
  intent: OAuthIntent;
};

/**
 * Binds the callback intent to the PKCE state generated by the provider auth
 * module. A callback cannot use an intent from a different OAuth round trip.
 */
function bindPostAuthFlow(url: string, flow: OAuthFlowInput): string {
  const oauthState = new URL(url).searchParams.get("state");
  if (!oauthState) {
    throw new Error("OAuth authorization URL did not include state");
  }
  setPostAuthRedirect({ ...flow, oauthState });
  return url;
}

/**
 * Begins the Google OAuth PKCE flow for sign-in and returns the authorization
 * URL to navigate to, or null when Google is not configured for this build.
 */
export async function startGoogleSignIn({ returnTo = "/" }: StartSignInOptions = {}): Promise<
  string | null
> {
  if (!isGoogleConfigured()) return null;
  const url = await startGoogleAuth({
    clientId: GOOGLE_CLIENT_ID,
    redirectUri: googleRedirectUri(window.location.origin),
    scope: GOOGLE_IDENTITY_SCOPE,
  });
  return bindPostAuthFlow(url, { intent: "sign-in", returnTo, provider: "google" });
}

/**
 * Begins the Outlook OAuth PKCE flow for sign-in and returns the authorization
 * URL to navigate to, or null when Outlook is not configured for this build.
 */
export async function startOutlookSignIn({ returnTo = "/" }: StartSignInOptions = {}): Promise<
  string | null
> {
  if (!isOutlookConfigured()) return null;
  const url = await startOutlookAuth({
    clientId: OUTLOOK_CLIENT_ID,
    redirectUri: outlookRedirectUri(window.location.origin),
    scope: OUTLOOK_IDENTITY_SCOPE,
  });
  return bindPostAuthFlow(url, { intent: "sign-in", returnTo, provider: "outlook" });
}

/**
 * Starts an identity-only Google flow that links a Google account to the
 * signed-in application account, so it can also be used to sign in.
 */
export async function startGoogleIdentityLink(): Promise<string | null> {
  if (!isGoogleConfigured()) return null;
  const url = await startGoogleAuth({
    clientId: GOOGLE_CLIENT_ID,
    redirectUri: googleRedirectUri(window.location.origin),
    scope: GOOGLE_IDENTITY_SCOPE,
  });
  return bindPostAuthFlow(url, {
    intent: "link-identity",
    returnTo: "/settings",
    provider: "google",
  });
}

/**
 * Starts an identity-only Outlook flow that links a Microsoft account to the
 * signed-in application account, so it can also be used to sign in.
 */
export async function startOutlookIdentityLink(): Promise<string | null> {
  if (!isOutlookConfigured()) return null;
  const url = await startOutlookAuth({
    clientId: OUTLOOK_CLIENT_ID,
    redirectUri: outlookRedirectUri(window.location.origin),
    scope: OUTLOOK_IDENTITY_SCOPE,
  });
  return bindPostAuthFlow(url, {
    intent: "link-identity",
    returnTo: "/settings",
    provider: "outlook",
  });
}

/**
 * Starts an explicit Google calendar-connection flow for the signed-in account.
 * The requested scopes include identity claims, because the server must verify
 * the provider identity before it marks the calendar as connected.
 */
export async function startGoogleCalendarConnection(): Promise<string | null> {
  if (!isGoogleConfigured()) return null;
  const url = await startGoogleAuth({
    clientId: GOOGLE_CLIENT_ID,
    redirectUri: googleRedirectUri(window.location.origin),
    scope: GOOGLE_CALENDAR_CONNECTION_SCOPE,
  });
  return bindPostAuthFlow(url, {
    intent: "connect-calendar",
    returnTo: "/settings",
    provider: "google",
  });
}

/**
 * Starts an explicit Outlook calendar-connection flow for the signed-in account.
 */
export async function startOutlookCalendarConnection(): Promise<string | null> {
  if (!isOutlookConfigured()) return null;
  const url = await startOutlookAuth({
    clientId: OUTLOOK_CLIENT_ID,
    redirectUri: outlookRedirectUri(window.location.origin),
    scope: OUTLOOK_CALENDAR_CONNECTION_SCOPE,
  });
  return bindPostAuthFlow(url, {
    intent: "connect-calendar",
    returnTo: "/settings",
    provider: "outlook",
  });
}
